---
services:
  home-ui:
    image: medkha/home-ui:${UI_TAG}
    container_name: home-ui
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.home.rule=Host(`home.medkha.com`)
        || Host(`www.home.medkha.com`)"
      - "traefik.http.routers.home.entrypoints=websecure"
      - "traefik.http.routers.home.tls=true"
      - "traefik.http.routers.home.tls.certresolver=letsencrypt"

      - "traefik.http.services.home.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
